/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Applicant type.
 */
public class Applicant {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer id;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String fisrtName;

    /**
     * Default constructor.
     */
    public Applicant() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  fisrtName  String value for fisrtName.
     */
    public Applicant(
            Integer id,
            String fisrtName) {
        this.id = id;
        this.fisrtName = fisrtName;
    }

    /**
     * Getter for Id.
     * ID of the applicant. To be used when updating the applicant details
     * @return Returns the Integer
     */
    @JsonGetter("id")
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * ID of the applicant. To be used when updating the applicant details
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for FisrtName.
     * First name of the applicant
     * @return Returns the String
     */
    @JsonGetter("fisrt_name")
    public String getFisrtName() {
        return fisrtName;
    }

    /**
     * Setter for FisrtName.
     * First name of the applicant
     * @param fisrtName Value for String
     */
    @JsonSetter("fisrt_name")
    public void setFisrtName(String fisrtName) {
        this.fisrtName = fisrtName;
    }

    /**
     * Converts this Applicant into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Applicant [" + "id=" + id + ", fisrtName=" + fisrtName + "]";
    }

    /**
     * Builds a new {@link Applicant.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Applicant.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .fisrtName(getFisrtName());
        return builder;
    }

    /**
     * Class to build instances of {@link Applicant}.
     */
    public static class Builder {
        private Integer id;
        private String fisrtName;



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for fisrtName.
         * @param  fisrtName  String value for fisrtName.
         * @return Builder
         */
        public Builder fisrtName(String fisrtName) {
            this.fisrtName = fisrtName;
            return this;
        }

        /**
         * Builds a new {@link Applicant} object using the set fields.
         * @return {@link Applicant}
         */
        public Applicant build() {
            return new Applicant(id, fisrtName);
        }
    }
}
