/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import in.credavenue.colenduat01api.DateTimeHelper;
import java.time.LocalDate;

/**
 * This is a model class for ClientsApiLoansAdvancePaymentsRequest type.
 */
public class ClientsApiLoansAdvancePaymentsRequest {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String instrumentNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String instrumentType;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String transactionType;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double amount;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private LocalDate transactionDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private LocalDate investorTransferDate;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double advanceOutstanding;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String comment;

    /**
     * Default constructor.
     */
    public ClientsApiLoansAdvancePaymentsRequest() {
    }

    /**
     * Initialization constructor.
     * @param  instrumentNumber  String value for instrumentNumber.
     * @param  instrumentType  String value for instrumentType.
     * @param  transactionType  String value for transactionType.
     * @param  amount  Double value for amount.
     * @param  transactionDate  LocalDate value for transactionDate.
     * @param  investorTransferDate  LocalDate value for investorTransferDate.
     * @param  advanceOutstanding  Double value for advanceOutstanding.
     * @param  comment  String value for comment.
     */
    public ClientsApiLoansAdvancePaymentsRequest(
            String instrumentNumber,
            String instrumentType,
            String transactionType,
            Double amount,
            LocalDate transactionDate,
            LocalDate investorTransferDate,
            Double advanceOutstanding,
            String comment) {
        this.instrumentNumber = instrumentNumber;
        this.instrumentType = instrumentType;
        this.transactionType = transactionType;
        this.amount = amount;
        this.transactionDate = transactionDate;
        this.investorTransferDate = investorTransferDate;
        this.advanceOutstanding = advanceOutstanding;
        this.comment = comment;
    }

    /**
     * Getter for InstrumentNumber.
     * UTR / Cheque Number
     * @return Returns the String
     */
    @JsonGetter("instrument_number")
    public String getInstrumentNumber() {
        return instrumentNumber;
    }

    /**
     * Setter for InstrumentNumber.
     * UTR / Cheque Number
     * @param instrumentNumber Value for String
     */
    @JsonSetter("instrument_number")
    public void setInstrumentNumber(String instrumentNumber) {
        this.instrumentNumber = instrumentNumber;
    }

    /**
     * Getter for InstrumentType.
     * RTGS / NEFT / UPI / Cheque
     * @return Returns the String
     */
    @JsonGetter("instrument_type")
    public String getInstrumentType() {
        return instrumentType;
    }

    /**
     * Setter for InstrumentType.
     * RTGS / NEFT / UPI / Cheque
     * @param instrumentType Value for String
     */
    @JsonSetter("instrument_type")
    public void setInstrumentType(String instrumentType) {
        this.instrumentType = instrumentType;
    }

    /**
     * Getter for TransactionType.
     * Credit / Refund
     * @return Returns the String
     */
    @JsonGetter("transaction_type")
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * Setter for TransactionType.
     * Credit / Refund
     * @param transactionType Value for String
     */
    @JsonSetter("transaction_type")
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType;
    }

    /**
     * Getter for Amount.
     * @return Returns the Double
     */
    @JsonGetter("amount")
    public Double getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for Double
     */
    @JsonSetter("amount")
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * Getter for TransactionDate.
     * Date when customer paid the amount (YYYY-MM-DD)
     * @return Returns the LocalDate
     */
    @JsonGetter("transaction_date")
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getTransactionDate() {
        return transactionDate;
    }

    /**
     * Setter for TransactionDate.
     * Date when customer paid the amount (YYYY-MM-DD)
     * @param transactionDate Value for LocalDate
     */
    @JsonSetter("transaction_date")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setTransactionDate(LocalDate transactionDate) {
        this.transactionDate = transactionDate;
    }

    /**
     * Getter for InvestorTransferDate.
     * Date when originator transferred the amount to investor (YYYY-MM-DD)
     * @return Returns the LocalDate
     */
    @JsonGetter("investor_transfer_date")
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getInvestorTransferDate() {
        return investorTransferDate;
    }

    /**
     * Setter for InvestorTransferDate.
     * Date when originator transferred the amount to investor (YYYY-MM-DD)
     * @param investorTransferDate Value for LocalDate
     */
    @JsonSetter("investor_transfer_date")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setInvestorTransferDate(LocalDate investorTransferDate) {
        this.investorTransferDate = investorTransferDate;
    }

    /**
     * Getter for AdvanceOutstanding.
     * Before this collection record to mention advance outstanding for that loan
     * @return Returns the Double
     */
    @JsonGetter("advance_outstanding")
    public Double getAdvanceOutstanding() {
        return advanceOutstanding;
    }

    /**
     * Setter for AdvanceOutstanding.
     * Before this collection record to mention advance outstanding for that loan
     * @param advanceOutstanding Value for Double
     */
    @JsonSetter("advance_outstanding")
    public void setAdvanceOutstanding(Double advanceOutstanding) {
        this.advanceOutstanding = advanceOutstanding;
    }

    /**
     * Getter for Comment.
     * @return Returns the String
     */
    @JsonGetter("comment")
    public String getComment() {
        return comment;
    }

    /**
     * Setter for Comment.
     * @param comment Value for String
     */
    @JsonSetter("comment")
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Converts this ClientsApiLoansAdvancePaymentsRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ClientsApiLoansAdvancePaymentsRequest [" + "instrumentNumber=" + instrumentNumber
                + ", instrumentType=" + instrumentType + ", transactionType=" + transactionType
                + ", amount=" + amount + ", transactionDate=" + transactionDate
                + ", investorTransferDate=" + investorTransferDate + ", advanceOutstanding="
                + advanceOutstanding + ", comment=" + comment + "]";
    }

    /**
     * Builds a new {@link ClientsApiLoansAdvancePaymentsRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ClientsApiLoansAdvancePaymentsRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .instrumentNumber(getInstrumentNumber())
                .instrumentType(getInstrumentType())
                .transactionType(getTransactionType())
                .amount(getAmount())
                .transactionDate(getTransactionDate())
                .investorTransferDate(getInvestorTransferDate())
                .advanceOutstanding(getAdvanceOutstanding())
                .comment(getComment());
        return builder;
    }

    /**
     * Class to build instances of {@link ClientsApiLoansAdvancePaymentsRequest}.
     */
    public static class Builder {
        private String instrumentNumber;
        private String instrumentType;
        private String transactionType;
        private Double amount;
        private LocalDate transactionDate;
        private LocalDate investorTransferDate;
        private Double advanceOutstanding;
        private String comment;



        /**
         * Setter for instrumentNumber.
         * @param  instrumentNumber  String value for instrumentNumber.
         * @return Builder
         */
        public Builder instrumentNumber(String instrumentNumber) {
            this.instrumentNumber = instrumentNumber;
            return this;
        }

        /**
         * Setter for instrumentType.
         * @param  instrumentType  String value for instrumentType.
         * @return Builder
         */
        public Builder instrumentType(String instrumentType) {
            this.instrumentType = instrumentType;
            return this;
        }

        /**
         * Setter for transactionType.
         * @param  transactionType  String value for transactionType.
         * @return Builder
         */
        public Builder transactionType(String transactionType) {
            this.transactionType = transactionType;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  Double value for amount.
         * @return Builder
         */
        public Builder amount(Double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for transactionDate.
         * @param  transactionDate  LocalDate value for transactionDate.
         * @return Builder
         */
        public Builder transactionDate(LocalDate transactionDate) {
            this.transactionDate = transactionDate;
            return this;
        }

        /**
         * Setter for investorTransferDate.
         * @param  investorTransferDate  LocalDate value for investorTransferDate.
         * @return Builder
         */
        public Builder investorTransferDate(LocalDate investorTransferDate) {
            this.investorTransferDate = investorTransferDate;
            return this;
        }

        /**
         * Setter for advanceOutstanding.
         * @param  advanceOutstanding  Double value for advanceOutstanding.
         * @return Builder
         */
        public Builder advanceOutstanding(Double advanceOutstanding) {
            this.advanceOutstanding = advanceOutstanding;
            return this;
        }

        /**
         * Setter for comment.
         * @param  comment  String value for comment.
         * @return Builder
         */
        public Builder comment(String comment) {
            this.comment = comment;
            return this;
        }

        /**
         * Builds a new {@link ClientsApiLoansAdvancePaymentsRequest} object using the set fields.
         * @return {@link ClientsApiLoansAdvancePaymentsRequest}
         */
        public ClientsApiLoansAdvancePaymentsRequest build() {
            return new ClientsApiLoansAdvancePaymentsRequest(instrumentNumber, instrumentType,
                    transactionType, amount, transactionDate, investorTransferDate,
                    advanceOutstanding, comment);
        }
    }
}
