/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import in.credavenue.colenduat01api.DateTimeHelper;
import java.time.LocalDate;

/**
 * This is a model class for ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest type.
 */
public class ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private LocalDate investorTransferDate;

    /**
     * Default constructor.
     */
    public ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest() {
    }

    /**
     * Initialization constructor.
     * @param  investorTransferDate  LocalDate value for investorTransferDate.
     */
    public ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest(
            LocalDate investorTransferDate) {
        this.investorTransferDate = investorTransferDate;
    }

    /**
     * Getter for InvestorTransferDate.
     * Date when originator transferred the amount to investor (YYYY-MM-DD)
     * @return Returns the LocalDate
     */
    @JsonGetter("investor_transfer_date")
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getInvestorTransferDate() {
        return investorTransferDate;
    }

    /**
     * Setter for InvestorTransferDate.
     * Date when originator transferred the amount to investor (YYYY-MM-DD)
     * @param investorTransferDate Value for LocalDate
     */
    @JsonSetter("investor_transfer_date")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setInvestorTransferDate(LocalDate investorTransferDate) {
        this.investorTransferDate = investorTransferDate;
    }

    /**
     * Converts this ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest [" + "investorTransferDate="
                + investorTransferDate + "]";
    }

    /**
     * Builds a new {@link ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .investorTransferDate(getInvestorTransferDate());
        return builder;
    }

    /**
     * Class to build instances of {@link ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest}.
     */
    public static class Builder {
        private LocalDate investorTransferDate;



        /**
         * Setter for investorTransferDate.
         * @param  investorTransferDate  LocalDate value for investorTransferDate.
         * @return Builder
         */
        public Builder investorTransferDate(LocalDate investorTransferDate) {
            this.investorTransferDate = investorTransferDate;
            return this;
        }

        /**
         * Builds a new {@link ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest} object using
         * the set fields.
         * @return {@link ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest}
         */
        public ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest build() {
            return new ClientsApiLoansAdvancePaymentsAdvancePaymentIdRequest(investorTransferDate);
        }
    }
}
