/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ClientsApiLoansRsRequest type.
 */
public class ClientsApiLoansRsRequest {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<RepaymentSchedule> repaymentSchedules;

    /**
     * Default constructor.
     */
    public ClientsApiLoansRsRequest() {
    }

    /**
     * Initialization constructor.
     * @param  repaymentSchedules  List of RepaymentSchedule value for repaymentSchedules.
     */
    public ClientsApiLoansRsRequest(
            List<RepaymentSchedule> repaymentSchedules) {
        this.repaymentSchedules = repaymentSchedules;
    }

    /**
     * Getter for RepaymentSchedules.
     * @return Returns the List of RepaymentSchedule
     */
    @JsonGetter("repayment_schedules")
    public List<RepaymentSchedule> getRepaymentSchedules() {
        return repaymentSchedules;
    }

    /**
     * Setter for RepaymentSchedules.
     * @param repaymentSchedules Value for List of RepaymentSchedule
     */
    @JsonSetter("repayment_schedules")
    public void setRepaymentSchedules(List<RepaymentSchedule> repaymentSchedules) {
        this.repaymentSchedules = repaymentSchedules;
    }

    /**
     * Converts this ClientsApiLoansRsRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ClientsApiLoansRsRequest [" + "repaymentSchedules=" + repaymentSchedules + "]";
    }

    /**
     * Builds a new {@link ClientsApiLoansRsRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ClientsApiLoansRsRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .repaymentSchedules(getRepaymentSchedules());
        return builder;
    }

    /**
     * Class to build instances of {@link ClientsApiLoansRsRequest}.
     */
    public static class Builder {
        private List<RepaymentSchedule> repaymentSchedules;



        /**
         * Setter for repaymentSchedules.
         * @param  repaymentSchedules  List of RepaymentSchedule value for repaymentSchedules.
         * @return Builder
         */
        public Builder repaymentSchedules(List<RepaymentSchedule> repaymentSchedules) {
            this.repaymentSchedules = repaymentSchedules;
            return this;
        }

        /**
         * Builds a new {@link ClientsApiLoansRsRequest} object using the set fields.
         * @return {@link ClientsApiLoansRsRequest}
         */
        public ClientsApiLoansRsRequest build() {
            return new ClientsApiLoansRsRequest(repaymentSchedules);
        }
    }
}
