/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ClientsApiInterestAccrualRequest type.
 */
public class ClientsApiInterestAccrualRequest {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String fileLink;

    /**
     * Default constructor.
     */
    public ClientsApiInterestAccrualRequest() {
    }

    /**
     * Initialization constructor.
     * @param  fileLink  String value for fileLink.
     */
    public ClientsApiInterestAccrualRequest(
            String fileLink) {
        this.fileLink = fileLink;
    }

    /**
     * Getter for FileLink.
     * @return Returns the String
     */
    @JsonGetter("file_link")
    public String getFileLink() {
        return fileLink;
    }

    /**
     * Setter for FileLink.
     * @param fileLink Value for String
     */
    @JsonSetter("file_link")
    public void setFileLink(String fileLink) {
        this.fileLink = fileLink;
    }

    /**
     * Converts this ClientsApiInterestAccrualRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ClientsApiInterestAccrualRequest [" + "fileLink=" + fileLink + "]";
    }

    /**
     * Builds a new {@link ClientsApiInterestAccrualRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ClientsApiInterestAccrualRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fileLink(getFileLink());
        return builder;
    }

    /**
     * Class to build instances of {@link ClientsApiInterestAccrualRequest}.
     */
    public static class Builder {
        private String fileLink;



        /**
         * Setter for fileLink.
         * @param  fileLink  String value for fileLink.
         * @return Builder
         */
        public Builder fileLink(String fileLink) {
            this.fileLink = fileLink;
            return this;
        }

        /**
         * Builds a new {@link ClientsApiInterestAccrualRequest} object using the set fields.
         * @return {@link ClientsApiInterestAccrualRequest}
         */
        public ClientsApiInterestAccrualRequest build() {
            return new ClientsApiInterestAccrualRequest(fileLink);
        }
    }
}
