/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import in.credavenue.colenduat01api.DateTimeHelper;
import java.time.LocalDate;
import java.util.List;

/**
 * This is a model class for CoApplicant type.
 */
public class CoApplicant {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String relationshipWithApplicant;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String firstName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String middleName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String lastName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String gender;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private LocalDate dateOfBirth;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer age;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String mobileNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String email;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String currentAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String currentCity;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String currentDistrict;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String currentState;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer currentPincode;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String residenceTypeCurrentAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer yearsOfStayInCurrentAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String permanentAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String permanentCity;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String permanentDistrict;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String permanentState;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer permanentPincode;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String residenceTypePermanentAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer yearsOfStayInPermanentAddress;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String maritalStatus;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String religion;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String nationality;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String fatherName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String motherName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String spouseName;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String educationQualification;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double annualIncome;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> incomeProofLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> bankStatement12MonthsLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String panNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> panLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String aadharNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> aadharLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String voterIdNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> votingIdLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String drivingLicenseNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> drivingLicenseLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String passportNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> passportLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> videoKycLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String videoKycProfileId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String videoKycAccountId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String videoKycKey;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String otherKycNumber;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> otherKycLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> rentAgreementLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> utilityBillsLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> photoLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer bureauScore;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private List<String> bureauReportLink;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer partnerScoreOnTheCoapplicant;

    /**
     * Default constructor.
     */
    public CoApplicant() {
    }

    /**
     * Initialization constructor.
     * @param  relationshipWithApplicant  String value for relationshipWithApplicant.
     * @param  firstName  String value for firstName.
     * @param  middleName  String value for middleName.
     * @param  lastName  String value for lastName.
     * @param  gender  String value for gender.
     * @param  dateOfBirth  LocalDate value for dateOfBirth.
     * @param  age  Integer value for age.
     * @param  mobileNumber  String value for mobileNumber.
     * @param  email  String value for email.
     * @param  currentAddress  String value for currentAddress.
     * @param  currentCity  String value for currentCity.
     * @param  currentDistrict  String value for currentDistrict.
     * @param  currentState  String value for currentState.
     * @param  currentPincode  Integer value for currentPincode.
     * @param  residenceTypeCurrentAddress  String value for residenceTypeCurrentAddress.
     * @param  yearsOfStayInCurrentAddress  Integer value for yearsOfStayInCurrentAddress.
     * @param  permanentAddress  String value for permanentAddress.
     * @param  permanentCity  String value for permanentCity.
     * @param  permanentDistrict  String value for permanentDistrict.
     * @param  permanentState  String value for permanentState.
     * @param  permanentPincode  Integer value for permanentPincode.
     * @param  residenceTypePermanentAddress  String value for residenceTypePermanentAddress.
     * @param  yearsOfStayInPermanentAddress  Integer value for yearsOfStayInPermanentAddress.
     * @param  maritalStatus  String value for maritalStatus.
     * @param  religion  String value for religion.
     * @param  nationality  String value for nationality.
     * @param  fatherName  String value for fatherName.
     * @param  motherName  String value for motherName.
     * @param  spouseName  String value for spouseName.
     * @param  educationQualification  String value for educationQualification.
     * @param  annualIncome  Double value for annualIncome.
     * @param  incomeProofLink  List of String value for incomeProofLink.
     * @param  bankStatement12MonthsLink  List of String value for bankStatement12MonthsLink.
     * @param  panNumber  String value for panNumber.
     * @param  panLink  List of String value for panLink.
     * @param  aadharNumber  String value for aadharNumber.
     * @param  aadharLink  List of String value for aadharLink.
     * @param  voterIdNumber  String value for voterIdNumber.
     * @param  votingIdLink  List of String value for votingIdLink.
     * @param  drivingLicenseNumber  String value for drivingLicenseNumber.
     * @param  drivingLicenseLink  List of String value for drivingLicenseLink.
     * @param  passportNumber  String value for passportNumber.
     * @param  passportLink  List of String value for passportLink.
     * @param  videoKycLink  List of String value for videoKycLink.
     * @param  videoKycProfileId  String value for videoKycProfileId.
     * @param  videoKycAccountId  String value for videoKycAccountId.
     * @param  videoKycKey  String value for videoKycKey.
     * @param  otherKycNumber  String value for otherKycNumber.
     * @param  otherKycLink  List of String value for otherKycLink.
     * @param  rentAgreementLink  List of String value for rentAgreementLink.
     * @param  utilityBillsLink  List of String value for utilityBillsLink.
     * @param  photoLink  List of String value for photoLink.
     * @param  bureauScore  Integer value for bureauScore.
     * @param  bureauReportLink  List of String value for bureauReportLink.
     * @param  partnerScoreOnTheCoapplicant  Integer value for partnerScoreOnTheCoapplicant.
     */
    public CoApplicant(
            String relationshipWithApplicant,
            String firstName,
            String middleName,
            String lastName,
            String gender,
            LocalDate dateOfBirth,
            Integer age,
            String mobileNumber,
            String email,
            String currentAddress,
            String currentCity,
            String currentDistrict,
            String currentState,
            Integer currentPincode,
            String residenceTypeCurrentAddress,
            Integer yearsOfStayInCurrentAddress,
            String permanentAddress,
            String permanentCity,
            String permanentDistrict,
            String permanentState,
            Integer permanentPincode,
            String residenceTypePermanentAddress,
            Integer yearsOfStayInPermanentAddress,
            String maritalStatus,
            String religion,
            String nationality,
            String fatherName,
            String motherName,
            String spouseName,
            String educationQualification,
            Double annualIncome,
            List<String> incomeProofLink,
            List<String> bankStatement12MonthsLink,
            String panNumber,
            List<String> panLink,
            String aadharNumber,
            List<String> aadharLink,
            String voterIdNumber,
            List<String> votingIdLink,
            String drivingLicenseNumber,
            List<String> drivingLicenseLink,
            String passportNumber,
            List<String> passportLink,
            List<String> videoKycLink,
            String videoKycProfileId,
            String videoKycAccountId,
            String videoKycKey,
            String otherKycNumber,
            List<String> otherKycLink,
            List<String> rentAgreementLink,
            List<String> utilityBillsLink,
            List<String> photoLink,
            Integer bureauScore,
            List<String> bureauReportLink,
            Integer partnerScoreOnTheCoapplicant) {
        this.relationshipWithApplicant = relationshipWithApplicant;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
        this.age = age;
        this.mobileNumber = mobileNumber;
        this.email = email;
        this.currentAddress = currentAddress;
        this.currentCity = currentCity;
        this.currentDistrict = currentDistrict;
        this.currentState = currentState;
        this.currentPincode = currentPincode;
        this.residenceTypeCurrentAddress = residenceTypeCurrentAddress;
        this.yearsOfStayInCurrentAddress = yearsOfStayInCurrentAddress;
        this.permanentAddress = permanentAddress;
        this.permanentCity = permanentCity;
        this.permanentDistrict = permanentDistrict;
        this.permanentState = permanentState;
        this.permanentPincode = permanentPincode;
        this.residenceTypePermanentAddress = residenceTypePermanentAddress;
        this.yearsOfStayInPermanentAddress = yearsOfStayInPermanentAddress;
        this.maritalStatus = maritalStatus;
        this.religion = religion;
        this.nationality = nationality;
        this.fatherName = fatherName;
        this.motherName = motherName;
        this.spouseName = spouseName;
        this.educationQualification = educationQualification;
        this.annualIncome = annualIncome;
        this.incomeProofLink = incomeProofLink;
        this.bankStatement12MonthsLink = bankStatement12MonthsLink;
        this.panNumber = panNumber;
        this.panLink = panLink;
        this.aadharNumber = aadharNumber;
        this.aadharLink = aadharLink;
        this.voterIdNumber = voterIdNumber;
        this.votingIdLink = votingIdLink;
        this.drivingLicenseNumber = drivingLicenseNumber;
        this.drivingLicenseLink = drivingLicenseLink;
        this.passportNumber = passportNumber;
        this.passportLink = passportLink;
        this.videoKycLink = videoKycLink;
        this.videoKycProfileId = videoKycProfileId;
        this.videoKycAccountId = videoKycAccountId;
        this.videoKycKey = videoKycKey;
        this.otherKycNumber = otherKycNumber;
        this.otherKycLink = otherKycLink;
        this.rentAgreementLink = rentAgreementLink;
        this.utilityBillsLink = utilityBillsLink;
        this.photoLink = photoLink;
        this.bureauScore = bureauScore;
        this.bureauReportLink = bureauReportLink;
        this.partnerScoreOnTheCoapplicant = partnerScoreOnTheCoapplicant;
    }

    /**
     * Getter for RelationshipWithApplicant.
     * @return Returns the String
     */
    @JsonGetter("relationship_with_applicant")
    public String getRelationshipWithApplicant() {
        return relationshipWithApplicant;
    }

    /**
     * Setter for RelationshipWithApplicant.
     * @param relationshipWithApplicant Value for String
     */
    @JsonSetter("relationship_with_applicant")
    public void setRelationshipWithApplicant(String relationshipWithApplicant) {
        this.relationshipWithApplicant = relationshipWithApplicant;
    }

    /**
     * Getter for FirstName.
     * First Name of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("first_name")
    public String getFirstName() {
        return firstName;
    }

    /**
     * Setter for FirstName.
     * First Name of the CoApplicant
     * @param firstName Value for String
     */
    @JsonSetter("first_name")
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for MiddleName.
     * Middle Name of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("middle_name")
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Setter for MiddleName.
     * Middle Name of the CoApplicant
     * @param middleName Value for String
     */
    @JsonSetter("middle_name")
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    /**
     * Getter for LastName.
     * Last Name of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("last_name")
    public String getLastName() {
        return lastName;
    }

    /**
     * Setter for LastName.
     * Last Name of the CoApplicant
     * @param lastName Value for String
     */
    @JsonSetter("last_name")
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for Gender.
     * M / F / O
     * @return Returns the String
     */
    @JsonGetter("gender")
    public String getGender() {
        return gender;
    }

    /**
     * Setter for Gender.
     * M / F / O
     * @param gender Value for String
     */
    @JsonSetter("gender")
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Getter for DateOfBirth.
     * Date of Birth (YYYY-MM-DD)
     * @return Returns the LocalDate
     */
    @JsonGetter("date_of_birth")
    @JsonSerialize(using = DateTimeHelper.SimpleDateSerializer.class)
    public LocalDate getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Setter for DateOfBirth.
     * Date of Birth (YYYY-MM-DD)
     * @param dateOfBirth Value for LocalDate
     */
    @JsonSetter("date_of_birth")
    @JsonDeserialize(using = DateTimeHelper.SimpleDateDeserializer.class)
    public void setDateOfBirth(LocalDate dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    /**
     * Getter for Age.
     * Age in years
     * @return Returns the Integer
     */
    @JsonGetter("age")
    public Integer getAge() {
        return age;
    }

    /**
     * Setter for Age.
     * Age in years
     * @param age Value for Integer
     */
    @JsonSetter("age")
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * Getter for MobileNumber.
     * Mobile Number of the CoApplicant (10 digits)
     * @return Returns the String
     */
    @JsonGetter("mobile_number")
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * Setter for MobileNumber.
     * Mobile Number of the CoApplicant (10 digits)
     * @param mobileNumber Value for String
     */
    @JsonSetter("mobile_number")
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    /**
     * Getter for Email.
     * Personal Email ID of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("email")
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * Personal Email ID of the CoApplicant
     * @param email Value for String
     */
    @JsonSetter("email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for CurrentAddress.
     * Free flowing text
     * @return Returns the String
     */
    @JsonGetter("current_address")
    public String getCurrentAddress() {
        return currentAddress;
    }

    /**
     * Setter for CurrentAddress.
     * Free flowing text
     * @param currentAddress Value for String
     */
    @JsonSetter("current_address")
    public void setCurrentAddress(String currentAddress) {
        this.currentAddress = currentAddress;
    }

    /**
     * Getter for CurrentCity.
     * City in which CoApplicant is currently residing
     * @return Returns the String
     */
    @JsonGetter("current_city")
    public String getCurrentCity() {
        return currentCity;
    }

    /**
     * Setter for CurrentCity.
     * City in which CoApplicant is currently residing
     * @param currentCity Value for String
     */
    @JsonSetter("current_city")
    public void setCurrentCity(String currentCity) {
        this.currentCity = currentCity;
    }

    /**
     * Getter for CurrentDistrict.
     * District in which CoApplicant is currently residing
     * @return Returns the String
     */
    @JsonGetter("current_district")
    public String getCurrentDistrict() {
        return currentDistrict;
    }

    /**
     * Setter for CurrentDistrict.
     * District in which CoApplicant is currently residing
     * @param currentDistrict Value for String
     */
    @JsonSetter("current_district")
    public void setCurrentDistrict(String currentDistrict) {
        this.currentDistrict = currentDistrict;
    }

    /**
     * Getter for CurrentState.
     * State in which CoApplicant is currently residing
     * @return Returns the String
     */
    @JsonGetter("current_state")
    public String getCurrentState() {
        return currentState;
    }

    /**
     * Setter for CurrentState.
     * State in which CoApplicant is currently residing
     * @param currentState Value for String
     */
    @JsonSetter("current_state")
    public void setCurrentState(String currentState) {
        this.currentState = currentState;
    }

    /**
     * Getter for CurrentPincode.
     * Pincode of the current address
     * @return Returns the Integer
     */
    @JsonGetter("current_pincode")
    public Integer getCurrentPincode() {
        return currentPincode;
    }

    /**
     * Setter for CurrentPincode.
     * Pincode of the current address
     * @param currentPincode Value for Integer
     */
    @JsonSetter("current_pincode")
    public void setCurrentPincode(Integer currentPincode) {
        this.currentPincode = currentPincode;
    }

    /**
     * Getter for ResidenceTypeCurrentAddress.
     * Rented / Owned / Leased
     * @return Returns the String
     */
    @JsonGetter("residence_type_current_address")
    public String getResidenceTypeCurrentAddress() {
        return residenceTypeCurrentAddress;
    }

    /**
     * Setter for ResidenceTypeCurrentAddress.
     * Rented / Owned / Leased
     * @param residenceTypeCurrentAddress Value for String
     */
    @JsonSetter("residence_type_current_address")
    public void setResidenceTypeCurrentAddress(String residenceTypeCurrentAddress) {
        this.residenceTypeCurrentAddress = residenceTypeCurrentAddress;
    }

    /**
     * Getter for YearsOfStayInCurrentAddress.
     * How many years stayed in the current address
     * @return Returns the Integer
     */
    @JsonGetter("years_of_stay_in_current_address")
    public Integer getYearsOfStayInCurrentAddress() {
        return yearsOfStayInCurrentAddress;
    }

    /**
     * Setter for YearsOfStayInCurrentAddress.
     * How many years stayed in the current address
     * @param yearsOfStayInCurrentAddress Value for Integer
     */
    @JsonSetter("years_of_stay_in_current_address")
    public void setYearsOfStayInCurrentAddress(Integer yearsOfStayInCurrentAddress) {
        this.yearsOfStayInCurrentAddress = yearsOfStayInCurrentAddress;
    }

    /**
     * Getter for PermanentAddress.
     * Free flowing text
     * @return Returns the String
     */
    @JsonGetter("permanent_address")
    public String getPermanentAddress() {
        return permanentAddress;
    }

    /**
     * Setter for PermanentAddress.
     * Free flowing text
     * @param permanentAddress Value for String
     */
    @JsonSetter("permanent_address")
    public void setPermanentAddress(String permanentAddress) {
        this.permanentAddress = permanentAddress;
    }

    /**
     * Getter for PermanentCity.
     * City in which CoApplicant is currently residing
     * @return Returns the String
     */
    @JsonGetter("permanent_city")
    public String getPermanentCity() {
        return permanentCity;
    }

    /**
     * Setter for PermanentCity.
     * City in which CoApplicant is currently residing
     * @param permanentCity Value for String
     */
    @JsonSetter("permanent_city")
    public void setPermanentCity(String permanentCity) {
        this.permanentCity = permanentCity;
    }

    /**
     * Getter for PermanentDistrict.
     * District in which CoApplicant is currently residing
     * @return Returns the String
     */
    @JsonGetter("permanent_district")
    public String getPermanentDistrict() {
        return permanentDistrict;
    }

    /**
     * Setter for PermanentDistrict.
     * District in which CoApplicant is currently residing
     * @param permanentDistrict Value for String
     */
    @JsonSetter("permanent_district")
    public void setPermanentDistrict(String permanentDistrict) {
        this.permanentDistrict = permanentDistrict;
    }

    /**
     * Getter for PermanentState.
     * State in which CoApplicant is currently residing
     * @return Returns the String
     */
    @JsonGetter("permanent_state")
    public String getPermanentState() {
        return permanentState;
    }

    /**
     * Setter for PermanentState.
     * State in which CoApplicant is currently residing
     * @param permanentState Value for String
     */
    @JsonSetter("permanent_state")
    public void setPermanentState(String permanentState) {
        this.permanentState = permanentState;
    }

    /**
     * Getter for PermanentPincode.
     * Pincode of the current address
     * @return Returns the Integer
     */
    @JsonGetter("permanent_pincode")
    public Integer getPermanentPincode() {
        return permanentPincode;
    }

    /**
     * Setter for PermanentPincode.
     * Pincode of the current address
     * @param permanentPincode Value for Integer
     */
    @JsonSetter("permanent_pincode")
    public void setPermanentPincode(Integer permanentPincode) {
        this.permanentPincode = permanentPincode;
    }

    /**
     * Getter for ResidenceTypePermanentAddress.
     * Rented / Owned / Leased
     * @return Returns the String
     */
    @JsonGetter("residence_type_permanent_address")
    public String getResidenceTypePermanentAddress() {
        return residenceTypePermanentAddress;
    }

    /**
     * Setter for ResidenceTypePermanentAddress.
     * Rented / Owned / Leased
     * @param residenceTypePermanentAddress Value for String
     */
    @JsonSetter("residence_type_permanent_address")
    public void setResidenceTypePermanentAddress(String residenceTypePermanentAddress) {
        this.residenceTypePermanentAddress = residenceTypePermanentAddress;
    }

    /**
     * Getter for YearsOfStayInPermanentAddress.
     * How many years stayed in the permanent address
     * @return Returns the Integer
     */
    @JsonGetter("years_of_stay_in_permanent_address")
    public Integer getYearsOfStayInPermanentAddress() {
        return yearsOfStayInPermanentAddress;
    }

    /**
     * Setter for YearsOfStayInPermanentAddress.
     * How many years stayed in the permanent address
     * @param yearsOfStayInPermanentAddress Value for Integer
     */
    @JsonSetter("years_of_stay_in_permanent_address")
    public void setYearsOfStayInPermanentAddress(Integer yearsOfStayInPermanentAddress) {
        this.yearsOfStayInPermanentAddress = yearsOfStayInPermanentAddress;
    }

    /**
     * Getter for MaritalStatus.
     * Married / Unmarried
     * @return Returns the String
     */
    @JsonGetter("marital_status")
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * Setter for MaritalStatus.
     * Married / Unmarried
     * @param maritalStatus Value for String
     */
    @JsonSetter("marital_status")
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    /**
     * Getter for Religion.
     * Religion of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("religion")
    public String getReligion() {
        return religion;
    }

    /**
     * Setter for Religion.
     * Religion of the CoApplicant
     * @param religion Value for String
     */
    @JsonSetter("religion")
    public void setReligion(String religion) {
        this.religion = religion;
    }

    /**
     * Getter for Nationality.
     * Nationality of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("nationality")
    public String getNationality() {
        return nationality;
    }

    /**
     * Setter for Nationality.
     * Nationality of the CoApplicant
     * @param nationality Value for String
     */
    @JsonSetter("nationality")
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    /**
     * Getter for FatherName.
     * Father Name of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("father_name")
    public String getFatherName() {
        return fatherName;
    }

    /**
     * Setter for FatherName.
     * Father Name of the CoApplicant
     * @param fatherName Value for String
     */
    @JsonSetter("father_name")
    public void setFatherName(String fatherName) {
        this.fatherName = fatherName;
    }

    /**
     * Getter for MotherName.
     * Mother Name of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("mother_name")
    public String getMotherName() {
        return motherName;
    }

    /**
     * Setter for MotherName.
     * Mother Name of the CoApplicant
     * @param motherName Value for String
     */
    @JsonSetter("mother_name")
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }

    /**
     * Getter for SpouseName.
     * Spouse Name of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("spouse_name")
    public String getSpouseName() {
        return spouseName;
    }

    /**
     * Setter for SpouseName.
     * Spouse Name of the CoApplicant
     * @param spouseName Value for String
     */
    @JsonSetter("spouse_name")
    public void setSpouseName(String spouseName) {
        this.spouseName = spouseName;
    }

    /**
     * Getter for EducationQualification.
     * Free flowing text
     * @return Returns the String
     */
    @JsonGetter("education_qualification")
    public String getEducationQualification() {
        return educationQualification;
    }

    /**
     * Setter for EducationQualification.
     * Free flowing text
     * @param educationQualification Value for String
     */
    @JsonSetter("education_qualification")
    public void setEducationQualification(String educationQualification) {
        this.educationQualification = educationQualification;
    }

    /**
     * Getter for AnnualIncome.
     * Annual Income of the CoApplicant (in Rupees)
     * @return Returns the Double
     */
    @JsonGetter("annual_income")
    public Double getAnnualIncome() {
        return annualIncome;
    }

    /**
     * Setter for AnnualIncome.
     * Annual Income of the CoApplicant (in Rupees)
     * @param annualIncome Value for Double
     */
    @JsonSetter("annual_income")
    public void setAnnualIncome(Double annualIncome) {
        this.annualIncome = annualIncome;
    }

    /**
     * Getter for IncomeProofLink.
     * @return Returns the List of String
     */
    @JsonGetter("income_proof_link")
    public List<String> getIncomeProofLink() {
        return incomeProofLink;
    }

    /**
     * Setter for IncomeProofLink.
     * @param incomeProofLink Value for List of String
     */
    @JsonSetter("income_proof_link")
    public void setIncomeProofLink(List<String> incomeProofLink) {
        this.incomeProofLink = incomeProofLink;
    }

    /**
     * Getter for BankStatement12MonthsLink.
     * Savings / Current Bank Account Statement for the Last 12 Months
     * @return Returns the List of String
     */
    @JsonGetter("bank_statement_12_months_link")
    public List<String> getBankStatement12MonthsLink() {
        return bankStatement12MonthsLink;
    }

    /**
     * Setter for BankStatement12MonthsLink.
     * Savings / Current Bank Account Statement for the Last 12 Months
     * @param bankStatement12MonthsLink Value for List of String
     */
    @JsonSetter("bank_statement_12_months_link")
    public void setBankStatement12MonthsLink(List<String> bankStatement12MonthsLink) {
        this.bankStatement12MonthsLink = bankStatement12MonthsLink;
    }

    /**
     * Getter for PanNumber.
     * PAN Number of the CoApplicant (10 digit Alphanumeric)
     * @return Returns the String
     */
    @JsonGetter("pan_number")
    public String getPanNumber() {
        return panNumber;
    }

    /**
     * Setter for PanNumber.
     * PAN Number of the CoApplicant (10 digit Alphanumeric)
     * @param panNumber Value for String
     */
    @JsonSetter("pan_number")
    public void setPanNumber(String panNumber) {
        this.panNumber = panNumber;
    }

    /**
     * Getter for PanLink.
     * PAN Document Link
     * @return Returns the List of String
     */
    @JsonGetter("pan_link")
    public List<String> getPanLink() {
        return panLink;
    }

    /**
     * Setter for PanLink.
     * PAN Document Link
     * @param panLink Value for List of String
     */
    @JsonSetter("pan_link")
    public void setPanLink(List<String> panLink) {
        this.panLink = panLink;
    }

    /**
     * Getter for AadharNumber.
     * Aadhar Number of the CoApplicant (12 digits)
     * @return Returns the String
     */
    @JsonGetter("aadhar_number")
    public String getAadharNumber() {
        return aadharNumber;
    }

    /**
     * Setter for AadharNumber.
     * Aadhar Number of the CoApplicant (12 digits)
     * @param aadharNumber Value for String
     */
    @JsonSetter("aadhar_number")
    public void setAadharNumber(String aadharNumber) {
        this.aadharNumber = aadharNumber;
    }

    /**
     * Getter for AadharLink.
     * Aadhar Document Link
     * @return Returns the List of String
     */
    @JsonGetter("aadhar_link")
    public List<String> getAadharLink() {
        return aadharLink;
    }

    /**
     * Setter for AadharLink.
     * Aadhar Document Link
     * @param aadharLink Value for List of String
     */
    @JsonSetter("aadhar_link")
    public void setAadharLink(List<String> aadharLink) {
        this.aadharLink = aadharLink;
    }

    /**
     * Getter for VoterIdNumber.
     * Voter ID Number of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("voter_id_number")
    public String getVoterIdNumber() {
        return voterIdNumber;
    }

    /**
     * Setter for VoterIdNumber.
     * Voter ID Number of the CoApplicant
     * @param voterIdNumber Value for String
     */
    @JsonSetter("voter_id_number")
    public void setVoterIdNumber(String voterIdNumber) {
        this.voterIdNumber = voterIdNumber;
    }

    /**
     * Getter for VotingIdLink.
     * Voter Document Link
     * @return Returns the List of String
     */
    @JsonGetter("voting_id_link")
    public List<String> getVotingIdLink() {
        return votingIdLink;
    }

    /**
     * Setter for VotingIdLink.
     * Voter Document Link
     * @param votingIdLink Value for List of String
     */
    @JsonSetter("voting_id_link")
    public void setVotingIdLink(List<String> votingIdLink) {
        this.votingIdLink = votingIdLink;
    }

    /**
     * Getter for DrivingLicenseNumber.
     * Driving License Number of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("driving_license_number")
    public String getDrivingLicenseNumber() {
        return drivingLicenseNumber;
    }

    /**
     * Setter for DrivingLicenseNumber.
     * Driving License Number of the CoApplicant
     * @param drivingLicenseNumber Value for String
     */
    @JsonSetter("driving_license_number")
    public void setDrivingLicenseNumber(String drivingLicenseNumber) {
        this.drivingLicenseNumber = drivingLicenseNumber;
    }

    /**
     * Getter for DrivingLicenseLink.
     * Driving License Document Link
     * @return Returns the List of String
     */
    @JsonGetter("driving_license_link")
    public List<String> getDrivingLicenseLink() {
        return drivingLicenseLink;
    }

    /**
     * Setter for DrivingLicenseLink.
     * Driving License Document Link
     * @param drivingLicenseLink Value for List of String
     */
    @JsonSetter("driving_license_link")
    public void setDrivingLicenseLink(List<String> drivingLicenseLink) {
        this.drivingLicenseLink = drivingLicenseLink;
    }

    /**
     * Getter for PassportNumber.
     * Passport Number of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("passport_number")
    public String getPassportNumber() {
        return passportNumber;
    }

    /**
     * Setter for PassportNumber.
     * Passport Number of the CoApplicant
     * @param passportNumber Value for String
     */
    @JsonSetter("passport_number")
    public void setPassportNumber(String passportNumber) {
        this.passportNumber = passportNumber;
    }

    /**
     * Getter for PassportLink.
     * Passport Document Link
     * @return Returns the List of String
     */
    @JsonGetter("passport_link")
    public List<String> getPassportLink() {
        return passportLink;
    }

    /**
     * Setter for PassportLink.
     * Passport Document Link
     * @param passportLink Value for List of String
     */
    @JsonSetter("passport_link")
    public void setPassportLink(List<String> passportLink) {
        this.passportLink = passportLink;
    }

    /**
     * Getter for VideoKycLink.
     * Video KYC of the Applicant
     * @return Returns the List of String
     */
    @JsonGetter("video_kyc_link")
    public List<String> getVideoKycLink() {
        return videoKycLink;
    }

    /**
     * Setter for VideoKycLink.
     * Video KYC of the Applicant
     * @param videoKycLink Value for List of String
     */
    @JsonSetter("video_kyc_link")
    public void setVideoKycLink(List<String> videoKycLink) {
        this.videoKycLink = videoKycLink;
    }

    /**
     * Getter for VideoKycProfileId.
     * Required if video KYC is done. Profile ID of the case as per the video KYC vendor
     * @return Returns the String
     */
    @JsonGetter("video_kyc_profile_id")
    public String getVideoKycProfileId() {
        return videoKycProfileId;
    }

    /**
     * Setter for VideoKycProfileId.
     * Required if video KYC is done. Profile ID of the case as per the video KYC vendor
     * @param videoKycProfileId Value for String
     */
    @JsonSetter("video_kyc_profile_id")
    public void setVideoKycProfileId(String videoKycProfileId) {
        this.videoKycProfileId = videoKycProfileId;
    }

    /**
     * Getter for VideoKycAccountId.
     * Required if video KYC is done. Account ID of the case as per the video KYC vendor
     * @return Returns the String
     */
    @JsonGetter("video_kyc_account_id")
    public String getVideoKycAccountId() {
        return videoKycAccountId;
    }

    /**
     * Setter for VideoKycAccountId.
     * Required if video KYC is done. Account ID of the case as per the video KYC vendor
     * @param videoKycAccountId Value for String
     */
    @JsonSetter("video_kyc_account_id")
    public void setVideoKycAccountId(String videoKycAccountId) {
        this.videoKycAccountId = videoKycAccountId;
    }

    /**
     * Getter for VideoKycKey.
     * Required if video KYC is done. Key as per the video KYC vendor
     * @return Returns the String
     */
    @JsonGetter("video_kyc_key")
    public String getVideoKycKey() {
        return videoKycKey;
    }

    /**
     * Setter for VideoKycKey.
     * Required if video KYC is done. Key as per the video KYC vendor
     * @param videoKycKey Value for String
     */
    @JsonSetter("video_kyc_key")
    public void setVideoKycKey(String videoKycKey) {
        this.videoKycKey = videoKycKey;
    }

    /**
     * Getter for OtherKycNumber.
     * KYC Number of the CoApplicant
     * @return Returns the String
     */
    @JsonGetter("other_kyc_number")
    public String getOtherKycNumber() {
        return otherKycNumber;
    }

    /**
     * Setter for OtherKycNumber.
     * KYC Number of the CoApplicant
     * @param otherKycNumber Value for String
     */
    @JsonSetter("other_kyc_number")
    public void setOtherKycNumber(String otherKycNumber) {
        this.otherKycNumber = otherKycNumber;
    }

    /**
     * Getter for OtherKycLink.
     * KYC Image of the CoApplicant
     * @return Returns the List of String
     */
    @JsonGetter("other_kyc_link")
    public List<String> getOtherKycLink() {
        return otherKycLink;
    }

    /**
     * Setter for OtherKycLink.
     * KYC Image of the CoApplicant
     * @param otherKycLink Value for List of String
     */
    @JsonSetter("other_kyc_link")
    public void setOtherKycLink(List<String> otherKycLink) {
        this.otherKycLink = otherKycLink;
    }

    /**
     * Getter for RentAgreementLink.
     * Rent Agreement Document Link
     * @return Returns the List of String
     */
    @JsonGetter("rent_agreement_link")
    public List<String> getRentAgreementLink() {
        return rentAgreementLink;
    }

    /**
     * Setter for RentAgreementLink.
     * Rent Agreement Document Link
     * @param rentAgreementLink Value for List of String
     */
    @JsonSetter("rent_agreement_link")
    public void setRentAgreementLink(List<String> rentAgreementLink) {
        this.rentAgreementLink = rentAgreementLink;
    }

    /**
     * Getter for UtilityBillsLink.
     * Utility Bills Copies (If any)
     * @return Returns the List of String
     */
    @JsonGetter("utility_bills_link")
    public List<String> getUtilityBillsLink() {
        return utilityBillsLink;
    }

    /**
     * Setter for UtilityBillsLink.
     * Utility Bills Copies (If any)
     * @param utilityBillsLink Value for List of String
     */
    @JsonSetter("utility_bills_link")
    public void setUtilityBillsLink(List<String> utilityBillsLink) {
        this.utilityBillsLink = utilityBillsLink;
    }

    /**
     * Getter for PhotoLink.
     * Photo Image of the CoApplicant
     * @return Returns the List of String
     */
    @JsonGetter("photo_link")
    public List<String> getPhotoLink() {
        return photoLink;
    }

    /**
     * Setter for PhotoLink.
     * Photo Image of the CoApplicant
     * @param photoLink Value for List of String
     */
    @JsonSetter("photo_link")
    public void setPhotoLink(List<String> photoLink) {
        this.photoLink = photoLink;
    }

    /**
     * Getter for BureauScore.
     * Bureau Score of the CoApplicant
     * @return Returns the Integer
     */
    @JsonGetter("bureau_score")
    public Integer getBureauScore() {
        return bureauScore;
    }

    /**
     * Setter for BureauScore.
     * Bureau Score of the CoApplicant
     * @param bureauScore Value for Integer
     */
    @JsonSetter("bureau_score")
    public void setBureauScore(Integer bureauScore) {
        this.bureauScore = bureauScore;
    }

    /**
     * Getter for BureauReportLink.
     * CoApplicant&#39;s Bureau Report PDF
     * @return Returns the List of String
     */
    @JsonGetter("bureau_report_link")
    public List<String> getBureauReportLink() {
        return bureauReportLink;
    }

    /**
     * Setter for BureauReportLink.
     * CoApplicant&#39;s Bureau Report PDF
     * @param bureauReportLink Value for List of String
     */
    @JsonSetter("bureau_report_link")
    public void setBureauReportLink(List<String> bureauReportLink) {
        this.bureauReportLink = bureauReportLink;
    }

    /**
     * Getter for PartnerScoreOnTheCoapplicant.
     * Score Captured by the Partner
     * @return Returns the Integer
     */
    @JsonGetter("partner_score_on_the_coapplicant")
    public Integer getPartnerScoreOnTheCoapplicant() {
        return partnerScoreOnTheCoapplicant;
    }

    /**
     * Setter for PartnerScoreOnTheCoapplicant.
     * Score Captured by the Partner
     * @param partnerScoreOnTheCoapplicant Value for Integer
     */
    @JsonSetter("partner_score_on_the_coapplicant")
    public void setPartnerScoreOnTheCoapplicant(Integer partnerScoreOnTheCoapplicant) {
        this.partnerScoreOnTheCoapplicant = partnerScoreOnTheCoapplicant;
    }

    /**
     * Converts this CoApplicant into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CoApplicant [" + "relationshipWithApplicant=" + relationshipWithApplicant
                + ", firstName=" + firstName + ", middleName=" + middleName + ", lastName="
                + lastName + ", gender=" + gender + ", dateOfBirth=" + dateOfBirth + ", age=" + age
                + ", mobileNumber=" + mobileNumber + ", email=" + email + ", currentAddress="
                + currentAddress + ", currentCity=" + currentCity + ", currentDistrict="
                + currentDistrict + ", currentState=" + currentState + ", currentPincode="
                + currentPincode + ", residenceTypeCurrentAddress=" + residenceTypeCurrentAddress
                + ", yearsOfStayInCurrentAddress=" + yearsOfStayInCurrentAddress
                + ", permanentAddress=" + permanentAddress + ", permanentCity=" + permanentCity
                + ", permanentDistrict=" + permanentDistrict + ", permanentState=" + permanentState
                + ", permanentPincode=" + permanentPincode + ", residenceTypePermanentAddress="
                + residenceTypePermanentAddress + ", yearsOfStayInPermanentAddress="
                + yearsOfStayInPermanentAddress + ", maritalStatus=" + maritalStatus + ", religion="
                + religion + ", nationality=" + nationality + ", fatherName=" + fatherName
                + ", motherName=" + motherName + ", spouseName=" + spouseName
                + ", educationQualification=" + educationQualification + ", annualIncome="
                + annualIncome + ", incomeProofLink=" + incomeProofLink
                + ", bankStatement12MonthsLink=" + bankStatement12MonthsLink + ", panNumber="
                + panNumber + ", panLink=" + panLink + ", aadharNumber=" + aadharNumber
                + ", aadharLink=" + aadharLink + ", voterIdNumber=" + voterIdNumber
                + ", votingIdLink=" + votingIdLink + ", drivingLicenseNumber="
                + drivingLicenseNumber + ", drivingLicenseLink=" + drivingLicenseLink
                + ", passportNumber=" + passportNumber + ", passportLink=" + passportLink
                + ", videoKycLink=" + videoKycLink + ", videoKycProfileId=" + videoKycProfileId
                + ", videoKycAccountId=" + videoKycAccountId + ", videoKycKey=" + videoKycKey
                + ", otherKycNumber=" + otherKycNumber + ", otherKycLink=" + otherKycLink
                + ", rentAgreementLink=" + rentAgreementLink + ", utilityBillsLink="
                + utilityBillsLink + ", photoLink=" + photoLink + ", bureauScore=" + bureauScore
                + ", bureauReportLink=" + bureauReportLink + ", partnerScoreOnTheCoapplicant="
                + partnerScoreOnTheCoapplicant + "]";
    }

    /**
     * Builds a new {@link CoApplicant.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CoApplicant.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .relationshipWithApplicant(getRelationshipWithApplicant())
                .firstName(getFirstName())
                .middleName(getMiddleName())
                .lastName(getLastName())
                .gender(getGender())
                .dateOfBirth(getDateOfBirth())
                .age(getAge())
                .mobileNumber(getMobileNumber())
                .email(getEmail())
                .currentAddress(getCurrentAddress())
                .currentCity(getCurrentCity())
                .currentDistrict(getCurrentDistrict())
                .currentState(getCurrentState())
                .currentPincode(getCurrentPincode())
                .residenceTypeCurrentAddress(getResidenceTypeCurrentAddress())
                .yearsOfStayInCurrentAddress(getYearsOfStayInCurrentAddress())
                .permanentAddress(getPermanentAddress())
                .permanentCity(getPermanentCity())
                .permanentDistrict(getPermanentDistrict())
                .permanentState(getPermanentState())
                .permanentPincode(getPermanentPincode())
                .residenceTypePermanentAddress(getResidenceTypePermanentAddress())
                .yearsOfStayInPermanentAddress(getYearsOfStayInPermanentAddress())
                .maritalStatus(getMaritalStatus())
                .religion(getReligion())
                .nationality(getNationality())
                .fatherName(getFatherName())
                .motherName(getMotherName())
                .spouseName(getSpouseName())
                .educationQualification(getEducationQualification())
                .annualIncome(getAnnualIncome())
                .incomeProofLink(getIncomeProofLink())
                .bankStatement12MonthsLink(getBankStatement12MonthsLink())
                .panNumber(getPanNumber())
                .panLink(getPanLink())
                .aadharNumber(getAadharNumber())
                .aadharLink(getAadharLink())
                .voterIdNumber(getVoterIdNumber())
                .votingIdLink(getVotingIdLink())
                .drivingLicenseNumber(getDrivingLicenseNumber())
                .drivingLicenseLink(getDrivingLicenseLink())
                .passportNumber(getPassportNumber())
                .passportLink(getPassportLink())
                .videoKycLink(getVideoKycLink())
                .videoKycProfileId(getVideoKycProfileId())
                .videoKycAccountId(getVideoKycAccountId())
                .videoKycKey(getVideoKycKey())
                .otherKycNumber(getOtherKycNumber())
                .otherKycLink(getOtherKycLink())
                .rentAgreementLink(getRentAgreementLink())
                .utilityBillsLink(getUtilityBillsLink())
                .photoLink(getPhotoLink())
                .bureauScore(getBureauScore())
                .bureauReportLink(getBureauReportLink())
                .partnerScoreOnTheCoapplicant(getPartnerScoreOnTheCoapplicant());
        return builder;
    }

    /**
     * Class to build instances of {@link CoApplicant}.
     */
    public static class Builder {
        private String relationshipWithApplicant;
        private String firstName;
        private String middleName;
        private String lastName;
        private String gender;
        private LocalDate dateOfBirth;
        private Integer age;
        private String mobileNumber;
        private String email;
        private String currentAddress;
        private String currentCity;
        private String currentDistrict;
        private String currentState;
        private Integer currentPincode;
        private String residenceTypeCurrentAddress;
        private Integer yearsOfStayInCurrentAddress;
        private String permanentAddress;
        private String permanentCity;
        private String permanentDistrict;
        private String permanentState;
        private Integer permanentPincode;
        private String residenceTypePermanentAddress;
        private Integer yearsOfStayInPermanentAddress;
        private String maritalStatus;
        private String religion;
        private String nationality;
        private String fatherName;
        private String motherName;
        private String spouseName;
        private String educationQualification;
        private Double annualIncome;
        private List<String> incomeProofLink;
        private List<String> bankStatement12MonthsLink;
        private String panNumber;
        private List<String> panLink;
        private String aadharNumber;
        private List<String> aadharLink;
        private String voterIdNumber;
        private List<String> votingIdLink;
        private String drivingLicenseNumber;
        private List<String> drivingLicenseLink;
        private String passportNumber;
        private List<String> passportLink;
        private List<String> videoKycLink;
        private String videoKycProfileId;
        private String videoKycAccountId;
        private String videoKycKey;
        private String otherKycNumber;
        private List<String> otherKycLink;
        private List<String> rentAgreementLink;
        private List<String> utilityBillsLink;
        private List<String> photoLink;
        private Integer bureauScore;
        private List<String> bureauReportLink;
        private Integer partnerScoreOnTheCoapplicant;



        /**
         * Setter for relationshipWithApplicant.
         * @param  relationshipWithApplicant  String value for relationshipWithApplicant.
         * @return Builder
         */
        public Builder relationshipWithApplicant(String relationshipWithApplicant) {
            this.relationshipWithApplicant = relationshipWithApplicant;
            return this;
        }

        /**
         * Setter for firstName.
         * @param  firstName  String value for firstName.
         * @return Builder
         */
        public Builder firstName(String firstName) {
            this.firstName = firstName;
            return this;
        }

        /**
         * Setter for middleName.
         * @param  middleName  String value for middleName.
         * @return Builder
         */
        public Builder middleName(String middleName) {
            this.middleName = middleName;
            return this;
        }

        /**
         * Setter for lastName.
         * @param  lastName  String value for lastName.
         * @return Builder
         */
        public Builder lastName(String lastName) {
            this.lastName = lastName;
            return this;
        }

        /**
         * Setter for gender.
         * @param  gender  String value for gender.
         * @return Builder
         */
        public Builder gender(String gender) {
            this.gender = gender;
            return this;
        }

        /**
         * Setter for dateOfBirth.
         * @param  dateOfBirth  LocalDate value for dateOfBirth.
         * @return Builder
         */
        public Builder dateOfBirth(LocalDate dateOfBirth) {
            this.dateOfBirth = dateOfBirth;
            return this;
        }

        /**
         * Setter for age.
         * @param  age  Integer value for age.
         * @return Builder
         */
        public Builder age(Integer age) {
            this.age = age;
            return this;
        }

        /**
         * Setter for mobileNumber.
         * @param  mobileNumber  String value for mobileNumber.
         * @return Builder
         */
        public Builder mobileNumber(String mobileNumber) {
            this.mobileNumber = mobileNumber;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for currentAddress.
         * @param  currentAddress  String value for currentAddress.
         * @return Builder
         */
        public Builder currentAddress(String currentAddress) {
            this.currentAddress = currentAddress;
            return this;
        }

        /**
         * Setter for currentCity.
         * @param  currentCity  String value for currentCity.
         * @return Builder
         */
        public Builder currentCity(String currentCity) {
            this.currentCity = currentCity;
            return this;
        }

        /**
         * Setter for currentDistrict.
         * @param  currentDistrict  String value for currentDistrict.
         * @return Builder
         */
        public Builder currentDistrict(String currentDistrict) {
            this.currentDistrict = currentDistrict;
            return this;
        }

        /**
         * Setter for currentState.
         * @param  currentState  String value for currentState.
         * @return Builder
         */
        public Builder currentState(String currentState) {
            this.currentState = currentState;
            return this;
        }

        /**
         * Setter for currentPincode.
         * @param  currentPincode  Integer value for currentPincode.
         * @return Builder
         */
        public Builder currentPincode(Integer currentPincode) {
            this.currentPincode = currentPincode;
            return this;
        }

        /**
         * Setter for residenceTypeCurrentAddress.
         * @param  residenceTypeCurrentAddress  String value for residenceTypeCurrentAddress.
         * @return Builder
         */
        public Builder residenceTypeCurrentAddress(String residenceTypeCurrentAddress) {
            this.residenceTypeCurrentAddress = residenceTypeCurrentAddress;
            return this;
        }

        /**
         * Setter for yearsOfStayInCurrentAddress.
         * @param  yearsOfStayInCurrentAddress  Integer value for yearsOfStayInCurrentAddress.
         * @return Builder
         */
        public Builder yearsOfStayInCurrentAddress(Integer yearsOfStayInCurrentAddress) {
            this.yearsOfStayInCurrentAddress = yearsOfStayInCurrentAddress;
            return this;
        }

        /**
         * Setter for permanentAddress.
         * @param  permanentAddress  String value for permanentAddress.
         * @return Builder
         */
        public Builder permanentAddress(String permanentAddress) {
            this.permanentAddress = permanentAddress;
            return this;
        }

        /**
         * Setter for permanentCity.
         * @param  permanentCity  String value for permanentCity.
         * @return Builder
         */
        public Builder permanentCity(String permanentCity) {
            this.permanentCity = permanentCity;
            return this;
        }

        /**
         * Setter for permanentDistrict.
         * @param  permanentDistrict  String value for permanentDistrict.
         * @return Builder
         */
        public Builder permanentDistrict(String permanentDistrict) {
            this.permanentDistrict = permanentDistrict;
            return this;
        }

        /**
         * Setter for permanentState.
         * @param  permanentState  String value for permanentState.
         * @return Builder
         */
        public Builder permanentState(String permanentState) {
            this.permanentState = permanentState;
            return this;
        }

        /**
         * Setter for permanentPincode.
         * @param  permanentPincode  Integer value for permanentPincode.
         * @return Builder
         */
        public Builder permanentPincode(Integer permanentPincode) {
            this.permanentPincode = permanentPincode;
            return this;
        }

        /**
         * Setter for residenceTypePermanentAddress.
         * @param  residenceTypePermanentAddress  String value for residenceTypePermanentAddress.
         * @return Builder
         */
        public Builder residenceTypePermanentAddress(String residenceTypePermanentAddress) {
            this.residenceTypePermanentAddress = residenceTypePermanentAddress;
            return this;
        }

        /**
         * Setter for yearsOfStayInPermanentAddress.
         * @param  yearsOfStayInPermanentAddress  Integer value for yearsOfStayInPermanentAddress.
         * @return Builder
         */
        public Builder yearsOfStayInPermanentAddress(Integer yearsOfStayInPermanentAddress) {
            this.yearsOfStayInPermanentAddress = yearsOfStayInPermanentAddress;
            return this;
        }

        /**
         * Setter for maritalStatus.
         * @param  maritalStatus  String value for maritalStatus.
         * @return Builder
         */
        public Builder maritalStatus(String maritalStatus) {
            this.maritalStatus = maritalStatus;
            return this;
        }

        /**
         * Setter for religion.
         * @param  religion  String value for religion.
         * @return Builder
         */
        public Builder religion(String religion) {
            this.religion = religion;
            return this;
        }

        /**
         * Setter for nationality.
         * @param  nationality  String value for nationality.
         * @return Builder
         */
        public Builder nationality(String nationality) {
            this.nationality = nationality;
            return this;
        }

        /**
         * Setter for fatherName.
         * @param  fatherName  String value for fatherName.
         * @return Builder
         */
        public Builder fatherName(String fatherName) {
            this.fatherName = fatherName;
            return this;
        }

        /**
         * Setter for motherName.
         * @param  motherName  String value for motherName.
         * @return Builder
         */
        public Builder motherName(String motherName) {
            this.motherName = motherName;
            return this;
        }

        /**
         * Setter for spouseName.
         * @param  spouseName  String value for spouseName.
         * @return Builder
         */
        public Builder spouseName(String spouseName) {
            this.spouseName = spouseName;
            return this;
        }

        /**
         * Setter for educationQualification.
         * @param  educationQualification  String value for educationQualification.
         * @return Builder
         */
        public Builder educationQualification(String educationQualification) {
            this.educationQualification = educationQualification;
            return this;
        }

        /**
         * Setter for annualIncome.
         * @param  annualIncome  Double value for annualIncome.
         * @return Builder
         */
        public Builder annualIncome(Double annualIncome) {
            this.annualIncome = annualIncome;
            return this;
        }

        /**
         * Setter for incomeProofLink.
         * @param  incomeProofLink  List of String value for incomeProofLink.
         * @return Builder
         */
        public Builder incomeProofLink(List<String> incomeProofLink) {
            this.incomeProofLink = incomeProofLink;
            return this;
        }

        /**
         * Setter for bankStatement12MonthsLink.
         * @param  bankStatement12MonthsLink  List of String value for bankStatement12MonthsLink.
         * @return Builder
         */
        public Builder bankStatement12MonthsLink(List<String> bankStatement12MonthsLink) {
            this.bankStatement12MonthsLink = bankStatement12MonthsLink;
            return this;
        }

        /**
         * Setter for panNumber.
         * @param  panNumber  String value for panNumber.
         * @return Builder
         */
        public Builder panNumber(String panNumber) {
            this.panNumber = panNumber;
            return this;
        }

        /**
         * Setter for panLink.
         * @param  panLink  List of String value for panLink.
         * @return Builder
         */
        public Builder panLink(List<String> panLink) {
            this.panLink = panLink;
            return this;
        }

        /**
         * Setter for aadharNumber.
         * @param  aadharNumber  String value for aadharNumber.
         * @return Builder
         */
        public Builder aadharNumber(String aadharNumber) {
            this.aadharNumber = aadharNumber;
            return this;
        }

        /**
         * Setter for aadharLink.
         * @param  aadharLink  List of String value for aadharLink.
         * @return Builder
         */
        public Builder aadharLink(List<String> aadharLink) {
            this.aadharLink = aadharLink;
            return this;
        }

        /**
         * Setter for voterIdNumber.
         * @param  voterIdNumber  String value for voterIdNumber.
         * @return Builder
         */
        public Builder voterIdNumber(String voterIdNumber) {
            this.voterIdNumber = voterIdNumber;
            return this;
        }

        /**
         * Setter for votingIdLink.
         * @param  votingIdLink  List of String value for votingIdLink.
         * @return Builder
         */
        public Builder votingIdLink(List<String> votingIdLink) {
            this.votingIdLink = votingIdLink;
            return this;
        }

        /**
         * Setter for drivingLicenseNumber.
         * @param  drivingLicenseNumber  String value for drivingLicenseNumber.
         * @return Builder
         */
        public Builder drivingLicenseNumber(String drivingLicenseNumber) {
            this.drivingLicenseNumber = drivingLicenseNumber;
            return this;
        }

        /**
         * Setter for drivingLicenseLink.
         * @param  drivingLicenseLink  List of String value for drivingLicenseLink.
         * @return Builder
         */
        public Builder drivingLicenseLink(List<String> drivingLicenseLink) {
            this.drivingLicenseLink = drivingLicenseLink;
            return this;
        }

        /**
         * Setter for passportNumber.
         * @param  passportNumber  String value for passportNumber.
         * @return Builder
         */
        public Builder passportNumber(String passportNumber) {
            this.passportNumber = passportNumber;
            return this;
        }

        /**
         * Setter for passportLink.
         * @param  passportLink  List of String value for passportLink.
         * @return Builder
         */
        public Builder passportLink(List<String> passportLink) {
            this.passportLink = passportLink;
            return this;
        }

        /**
         * Setter for videoKycLink.
         * @param  videoKycLink  List of String value for videoKycLink.
         * @return Builder
         */
        public Builder videoKycLink(List<String> videoKycLink) {
            this.videoKycLink = videoKycLink;
            return this;
        }

        /**
         * Setter for videoKycProfileId.
         * @param  videoKycProfileId  String value for videoKycProfileId.
         * @return Builder
         */
        public Builder videoKycProfileId(String videoKycProfileId) {
            this.videoKycProfileId = videoKycProfileId;
            return this;
        }

        /**
         * Setter for videoKycAccountId.
         * @param  videoKycAccountId  String value for videoKycAccountId.
         * @return Builder
         */
        public Builder videoKycAccountId(String videoKycAccountId) {
            this.videoKycAccountId = videoKycAccountId;
            return this;
        }

        /**
         * Setter for videoKycKey.
         * @param  videoKycKey  String value for videoKycKey.
         * @return Builder
         */
        public Builder videoKycKey(String videoKycKey) {
            this.videoKycKey = videoKycKey;
            return this;
        }

        /**
         * Setter for otherKycNumber.
         * @param  otherKycNumber  String value for otherKycNumber.
         * @return Builder
         */
        public Builder otherKycNumber(String otherKycNumber) {
            this.otherKycNumber = otherKycNumber;
            return this;
        }

        /**
         * Setter for otherKycLink.
         * @param  otherKycLink  List of String value for otherKycLink.
         * @return Builder
         */
        public Builder otherKycLink(List<String> otherKycLink) {
            this.otherKycLink = otherKycLink;
            return this;
        }

        /**
         * Setter for rentAgreementLink.
         * @param  rentAgreementLink  List of String value for rentAgreementLink.
         * @return Builder
         */
        public Builder rentAgreementLink(List<String> rentAgreementLink) {
            this.rentAgreementLink = rentAgreementLink;
            return this;
        }

        /**
         * Setter for utilityBillsLink.
         * @param  utilityBillsLink  List of String value for utilityBillsLink.
         * @return Builder
         */
        public Builder utilityBillsLink(List<String> utilityBillsLink) {
            this.utilityBillsLink = utilityBillsLink;
            return this;
        }

        /**
         * Setter for photoLink.
         * @param  photoLink  List of String value for photoLink.
         * @return Builder
         */
        public Builder photoLink(List<String> photoLink) {
            this.photoLink = photoLink;
            return this;
        }

        /**
         * Setter for bureauScore.
         * @param  bureauScore  Integer value for bureauScore.
         * @return Builder
         */
        public Builder bureauScore(Integer bureauScore) {
            this.bureauScore = bureauScore;
            return this;
        }

        /**
         * Setter for bureauReportLink.
         * @param  bureauReportLink  List of String value for bureauReportLink.
         * @return Builder
         */
        public Builder bureauReportLink(List<String> bureauReportLink) {
            this.bureauReportLink = bureauReportLink;
            return this;
        }

        /**
         * Setter for partnerScoreOnTheCoapplicant.
         * @param  partnerScoreOnTheCoapplicant  Integer value for partnerScoreOnTheCoapplicant.
         * @return Builder
         */
        public Builder partnerScoreOnTheCoapplicant(Integer partnerScoreOnTheCoapplicant) {
            this.partnerScoreOnTheCoapplicant = partnerScoreOnTheCoapplicant;
            return this;
        }

        /**
         * Builds a new {@link CoApplicant} object using the set fields.
         * @return {@link CoApplicant}
         */
        public CoApplicant build() {
            return new CoApplicant(relationshipWithApplicant, firstName, middleName, lastName,
                    gender, dateOfBirth, age, mobileNumber, email, currentAddress, currentCity,
                    currentDistrict, currentState, currentPincode, residenceTypeCurrentAddress,
                    yearsOfStayInCurrentAddress, permanentAddress, permanentCity, permanentDistrict,
                    permanentState, permanentPincode, residenceTypePermanentAddress,
                    yearsOfStayInPermanentAddress, maritalStatus, religion, nationality, fatherName,
                    motherName, spouseName, educationQualification, annualIncome, incomeProofLink,
                    bankStatement12MonthsLink, panNumber, panLink, aadharNumber, aadharLink,
                    voterIdNumber, votingIdLink, drivingLicenseNumber, drivingLicenseLink,
                    passportNumber, passportLink, videoKycLink, videoKycProfileId,
                    videoKycAccountId, videoKycKey, otherKycNumber, otherKycLink, rentAgreementLink,
                    utilityBillsLink, photoLink, bureauScore, bureauReportLink,
                    partnerScoreOnTheCoapplicant);
        }
    }
}
