/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateLoan201 type.
 */
public class CreateLoan201 {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String clientLoanId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String status;

    /**
     * Default constructor.
     */
    public CreateLoan201() {
    }

    /**
     * Initialization constructor.
     * @param  clientLoanId  String value for clientLoanId.
     * @param  status  String value for status.
     */
    public CreateLoan201(
            String clientLoanId,
            String status) {
        this.clientLoanId = clientLoanId;
        this.status = status;
    }

    /**
     * Getter for ClientLoanId.
     * Unique identifier for the loan
     * @return Returns the String
     */
    @JsonGetter("client_loan_id")
    public String getClientLoanId() {
        return clientLoanId;
    }

    /**
     * Setter for ClientLoanId.
     * Unique identifier for the loan
     * @param clientLoanId Value for String
     */
    @JsonSetter("client_loan_id")
    public void setClientLoanId(String clientLoanId) {
        this.clientLoanId = clientLoanId;
    }

    /**
     * Getter for Status.
     * Current status of the loan
     * @return Returns the String
     */
    @JsonGetter("status")
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Current status of the loan
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Converts this CreateLoan201 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateLoan201 [" + "clientLoanId=" + clientLoanId + ", status=" + status + "]";
    }

    /**
     * Builds a new {@link CreateLoan201.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateLoan201.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .clientLoanId(getClientLoanId())
                .status(getStatus());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateLoan201}.
     */
    public static class Builder {
        private String clientLoanId;
        private String status;



        /**
         * Setter for clientLoanId.
         * @param  clientLoanId  String value for clientLoanId.
         * @return Builder
         */
        public Builder clientLoanId(String clientLoanId) {
            this.clientLoanId = clientLoanId;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Builds a new {@link CreateLoan201} object using the set fields.
         * @return {@link CreateLoan201}
         */
        public CreateLoan201 build() {
            return new CreateLoan201(clientLoanId, status);
        }
    }
}
