/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CreateCollection201 type.
 */
public class CreateCollection201 {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String clientLoanId;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double amount;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer installmentNo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String emiClosed;

    /**
     * Default constructor.
     */
    public CreateCollection201() {
    }

    /**
     * Initialization constructor.
     * @param  clientLoanId  String value for clientLoanId.
     * @param  amount  Double value for amount.
     * @param  installmentNo  Integer value for installmentNo.
     * @param  emiClosed  String value for emiClosed.
     */
    public CreateCollection201(
            String clientLoanId,
            Double amount,
            Integer installmentNo,
            String emiClosed) {
        this.clientLoanId = clientLoanId;
        this.amount = amount;
        this.installmentNo = installmentNo;
        this.emiClosed = emiClosed;
    }

    /**
     * Getter for ClientLoanId.
     * Client_loan_id as provided during loan creation
     * @return Returns the String
     */
    @JsonGetter("client_loan_id")
    public String getClientLoanId() {
        return clientLoanId;
    }

    /**
     * Setter for ClientLoanId.
     * Client_loan_id as provided during loan creation
     * @param clientLoanId Value for String
     */
    @JsonSetter("client_loan_id")
    public void setClientLoanId(String clientLoanId) {
        this.clientLoanId = clientLoanId;
    }

    /**
     * Getter for Amount.
     * Amount
     * @return Returns the Double
     */
    @JsonGetter("amount")
    public Double getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * Amount
     * @param amount Value for Double
     */
    @JsonSetter("amount")
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * Getter for InstallmentNo.
     * Installment no
     * @return Returns the Integer
     */
    @JsonGetter("installment_no")
    public Integer getInstallmentNo() {
        return installmentNo;
    }

    /**
     * Setter for InstallmentNo.
     * Installment no
     * @param installmentNo Value for Integer
     */
    @JsonSetter("installment_no")
    public void setInstallmentNo(Integer installmentNo) {
        this.installmentNo = installmentNo;
    }

    /**
     * Getter for EmiClosed.
     * Emi closed flag
     * @return Returns the String
     */
    @JsonGetter("emi_closed")
    public String getEmiClosed() {
        return emiClosed;
    }

    /**
     * Setter for EmiClosed.
     * Emi closed flag
     * @param emiClosed Value for String
     */
    @JsonSetter("emi_closed")
    public void setEmiClosed(String emiClosed) {
        this.emiClosed = emiClosed;
    }

    /**
     * Converts this CreateCollection201 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CreateCollection201 [" + "clientLoanId=" + clientLoanId + ", amount=" + amount
                + ", installmentNo=" + installmentNo + ", emiClosed=" + emiClosed + "]";
    }

    /**
     * Builds a new {@link CreateCollection201.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CreateCollection201.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .clientLoanId(getClientLoanId())
                .amount(getAmount())
                .installmentNo(getInstallmentNo())
                .emiClosed(getEmiClosed());
        return builder;
    }

    /**
     * Class to build instances of {@link CreateCollection201}.
     */
    public static class Builder {
        private String clientLoanId;
        private Double amount;
        private Integer installmentNo;
        private String emiClosed;



        /**
         * Setter for clientLoanId.
         * @param  clientLoanId  String value for clientLoanId.
         * @return Builder
         */
        public Builder clientLoanId(String clientLoanId) {
            this.clientLoanId = clientLoanId;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  Double value for amount.
         * @return Builder
         */
        public Builder amount(Double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for installmentNo.
         * @param  installmentNo  Integer value for installmentNo.
         * @return Builder
         */
        public Builder installmentNo(Integer installmentNo) {
            this.installmentNo = installmentNo;
            return this;
        }

        /**
         * Setter for emiClosed.
         * @param  emiClosed  String value for emiClosed.
         * @return Builder
         */
        public Builder emiClosed(String emiClosed) {
            this.emiClosed = emiClosed;
            return this;
        }

        /**
         * Builds a new {@link CreateCollection201} object using the set fields.
         * @return {@link CreateCollection201}
         */
        public CreateCollection201 build() {
            return new CreateCollection201(clientLoanId, amount, installmentNo, emiClosed);
        }
    }
}
