/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GetPayment200 type.
 */
public class GetPayment200 {
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer id;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private String referenceNo;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double principal;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double interest;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Double feeCharges;
    @JsonInclude(JsonInclude.Include.NON_NULL)
    private Integer installmentNo;

    /**
     * Default constructor.
     */
    public GetPayment200() {
    }

    /**
     * Initialization constructor.
     * @param  id  Integer value for id.
     * @param  referenceNo  String value for referenceNo.
     * @param  principal  Double value for principal.
     * @param  interest  Double value for interest.
     * @param  feeCharges  Double value for feeCharges.
     * @param  installmentNo  Integer value for installmentNo.
     */
    public GetPayment200(
            Integer id,
            String referenceNo,
            Double principal,
            Double interest,
            Double feeCharges,
            Integer installmentNo) {
        this.id = id;
        this.referenceNo = referenceNo;
        this.principal = principal;
        this.interest = interest;
        this.feeCharges = feeCharges;
        this.installmentNo = installmentNo;
    }

    /**
     * Getter for Id.
     * @return Returns the Integer
     */
    @JsonGetter("id")
    public Integer getId() {
        return id;
    }

    /**
     * Setter for Id.
     * @param id Value for Integer
     */
    @JsonSetter("id")
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for ReferenceNo.
     * @return Returns the String
     */
    @JsonGetter("reference_no")
    public String getReferenceNo() {
        return referenceNo;
    }

    /**
     * Setter for ReferenceNo.
     * @param referenceNo Value for String
     */
    @JsonSetter("reference_no")
    public void setReferenceNo(String referenceNo) {
        this.referenceNo = referenceNo;
    }

    /**
     * Getter for Principal.
     * @return Returns the Double
     */
    @JsonGetter("principal")
    public Double getPrincipal() {
        return principal;
    }

    /**
     * Setter for Principal.
     * @param principal Value for Double
     */
    @JsonSetter("principal")
    public void setPrincipal(Double principal) {
        this.principal = principal;
    }

    /**
     * Getter for Interest.
     * @return Returns the Double
     */
    @JsonGetter("interest")
    public Double getInterest() {
        return interest;
    }

    /**
     * Setter for Interest.
     * @param interest Value for Double
     */
    @JsonSetter("interest")
    public void setInterest(Double interest) {
        this.interest = interest;
    }

    /**
     * Getter for FeeCharges.
     * @return Returns the Double
     */
    @JsonGetter("fee_charges")
    public Double getFeeCharges() {
        return feeCharges;
    }

    /**
     * Setter for FeeCharges.
     * @param feeCharges Value for Double
     */
    @JsonSetter("fee_charges")
    public void setFeeCharges(Double feeCharges) {
        this.feeCharges = feeCharges;
    }

    /**
     * Getter for InstallmentNo.
     * @return Returns the Integer
     */
    @JsonGetter("installment_no")
    public Integer getInstallmentNo() {
        return installmentNo;
    }

    /**
     * Setter for InstallmentNo.
     * @param installmentNo Value for Integer
     */
    @JsonSetter("installment_no")
    public void setInstallmentNo(Integer installmentNo) {
        this.installmentNo = installmentNo;
    }

    /**
     * Converts this GetPayment200 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetPayment200 [" + "id=" + id + ", referenceNo=" + referenceNo + ", principal="
                + principal + ", interest=" + interest + ", feeCharges=" + feeCharges
                + ", installmentNo=" + installmentNo + "]";
    }

    /**
     * Builds a new {@link GetPayment200.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetPayment200.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .referenceNo(getReferenceNo())
                .principal(getPrincipal())
                .interest(getInterest())
                .feeCharges(getFeeCharges())
                .installmentNo(getInstallmentNo());
        return builder;
    }

    /**
     * Class to build instances of {@link GetPayment200}.
     */
    public static class Builder {
        private Integer id;
        private String referenceNo;
        private Double principal;
        private Double interest;
        private Double feeCharges;
        private Integer installmentNo;



        /**
         * Setter for id.
         * @param  id  Integer value for id.
         * @return Builder
         */
        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for referenceNo.
         * @param  referenceNo  String value for referenceNo.
         * @return Builder
         */
        public Builder referenceNo(String referenceNo) {
            this.referenceNo = referenceNo;
            return this;
        }

        /**
         * Setter for principal.
         * @param  principal  Double value for principal.
         * @return Builder
         */
        public Builder principal(Double principal) {
            this.principal = principal;
            return this;
        }

        /**
         * Setter for interest.
         * @param  interest  Double value for interest.
         * @return Builder
         */
        public Builder interest(Double interest) {
            this.interest = interest;
            return this;
        }

        /**
         * Setter for feeCharges.
         * @param  feeCharges  Double value for feeCharges.
         * @return Builder
         */
        public Builder feeCharges(Double feeCharges) {
            this.feeCharges = feeCharges;
            return this;
        }

        /**
         * Setter for installmentNo.
         * @param  installmentNo  Integer value for installmentNo.
         * @return Builder
         */
        public Builder installmentNo(Integer installmentNo) {
            this.installmentNo = installmentNo;
            return this;
        }

        /**
         * Builds a new {@link GetPayment200} object using the set fields.
         * @return {@link GetPayment200}
         */
        public GetPayment200 build() {
            return new GetPayment200(id, referenceNo, principal, interest, feeCharges,
                    installmentNo);
        }
    }
}
