/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import in.credavenue.colenduat01api.http.client.HttpContext;
import in.credavenue.colenduat01api.models.Error;

/**
 * This is a model class for UnauthorizedException type.
 */
public class UnauthorizedException
        extends ApiException {
    private static final long serialVersionUID = -101703086555406294L;
    private Error error;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The http context of the API exception
     */
    public UnauthorizedException(String reason, HttpContext context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the Error
     */
    @JsonGetter("error")
    public Error getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for Error
     */
    @JsonSetter("error")
    private void setError(Error error) {
        this.error = error;
    }
}
