/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api.controllers;

import in.credavenue.colenduat01api.Environment;
import in.credavenue.colenduat01api.KrazybeeClient;
import in.credavenue.colenduat01api.testing.HttpCallbackCatcher;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Rule;
import org.junit.rules.Timeout;

/**
 * Base class for all test cases.
 */
public class BaseControllerTest {
    /**
     * Test configuration.
     */
    public static final int REQUEST_TIMEOUT = 30;

    public static final double ASSERT_PRECISION = 0.01;
    
    /**
     * Global rules for tests.
     */
    @Rule
    public Timeout globalTimeout = Timeout.seconds(REQUEST_TIMEOUT);
    
    /**
     * Test fixtures,
     * Used to serve as HttpCallback and to capture request & response.
     */

    protected static HttpCallbackCatcher httpResponse;
    
    /**
     * Setup test.
     */
    @BeforeClass
    public static void setUp() throws Exception {
        httpResponse = new HttpCallbackCatcher(); 
    }

    /**
     * Tear down test.
     */
    @AfterClass
    public static void tearDown() throws Exception {
        httpResponse = null;
    }

    /**
     * Create test configuration from Environment variables.
     */
    protected static KrazybeeClient createConfigurationFromEnvironment() {
        KrazybeeClient.Builder builder = new KrazybeeClient.Builder();

        final String environment = System.getenv("KRAZYBEE_LIB_ENVIRONMENT");
        final String host = System.getenv("KRAZYBEE_LIB_HOST");
        final String timeout = System.getenv("KRAZYBEE_LIB_TIMEOUT");
        final String apiKey = System.getenv("KRAZYBEE_LIB_API_KEY");

        if (apiKey != null) {
            builder.customHeaderAuthenticationCredentials(apiKey);
        }
        if (environment != null) {
            builder.environment(Environment.fromString(environment));
        }
        if (host != null) {
            builder.host(host);
        }
        if (timeout != null) {
            builder.httpClientConfig(configBuilder -> configBuilder.timeout(
                    Long.parseLong(timeout)));
        }
        return builder.build();
    }

    
    /**
     * Create test configuration.
     */
    protected static KrazybeeClient createConfiguration() {
        // Set Configuration parameters for test execution
        KrazybeeClient config = createConfigurationFromEnvironment();
        config = config.newBuilder()
                .httpCallback(httpResponse)
                .build();
        return config;
    }
}
