/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api;

import in.credavenue.colenduat01api.http.request.HttpRequest;
import java.util.concurrent.CompletableFuture;

public class CustomHeaderAuthenticationManager implements AuthManager, CustomHeaderAuthenticationCredentials {

    private String apiKey;

    /**
     * Constructor that sets custom header parameters.
     */
    public CustomHeaderAuthenticationManager(String apiKey) {
        this.apiKey = apiKey;
    }

    /**
     * String value for apiKey.
     * @return apiKey
     */
    public String getApiKey() {
        return apiKey;
    }

    /**
     * Checks if provided credentials matched with existing ones.
     * @param apiKey String value for credentials.
     * @return true if credentials matched.
     */
    public boolean equals(String apiKey) {
        return apiKey.equals(getApiKey());
    }

    /**
     * Converts this CustomHeaderAuthenticationManager into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CustomHeaderAuthenticationManager [" + "apiKey=" + apiKey + "]";
    }

    /**
     * Adds custom header parameters (if present) to the given HttpRequest.
     */
    public HttpRequest apply(HttpRequest httpRequest) {
        httpRequest.getHeaders().add("api_key", apiKey);
        return httpRequest;
    }

    /**
     * Adds custom header parameters (if present) to the given HttpRequest.
     */
    public CompletableFuture<HttpRequest> applyAsync(HttpRequest httpRequest) {
        return CompletableFuture.completedFuture(apply(httpRequest));
    }
}
