/*
 * KrazybeeLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package in.credavenue.colenduat01api;

import in.credavenue.colenduat01api.controllers.APIController;
import in.credavenue.colenduat01api.http.client.HttpCallback;
import in.credavenue.colenduat01api.http.client.HttpClient;
import in.credavenue.colenduat01api.http.client.HttpClientConfiguration;
import in.credavenue.colenduat01api.http.client.OkClient;
import in.credavenue.colenduat01api.http.client.ReadonlyHttpClientConfiguration;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class KrazybeeClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private APIController client;

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * For UAT environment
     */
    private final String host;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * CustomHeaderAuthenticationManager.
     */
    private CustomHeaderAuthenticationManager customHeaderAuthenticationManager;

    /**
     * Map of authentication Managers.
     */
    private Map<String, AuthManager> authManagers;

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private KrazybeeClient(Environment environment, String host, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, String apiKey,
            Map<String, AuthManager> authManagers, HttpCallback httpCallback) {
        this.environment = environment;
        this.host = host;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;

        this.authManagers = (authManagers == null) ? new HashMap<>() : new HashMap<>(authManagers);
        if (this.authManagers.containsKey("global")) {
            this.customHeaderAuthenticationManager =
                    (CustomHeaderAuthenticationManager) this.authManagers.get("global");
        }

        if (!this.authManagers.containsKey("global")
                || !getCustomHeaderAuthenticationCredentials().equals(apiKey)) {
            this.customHeaderAuthenticationManager = new CustomHeaderAuthenticationManager(
                    apiKey);
            this.authManagers.put("global", customHeaderAuthenticationManager);
        }

        client = new APIController(this, this.httpClient, this.authManagers, this.httpCallback);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of APIController.
     * @return client
     */
    public APIController getAPIController() {
        return client;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * For UAT environment
     * @return host
     */
    public String getHost() {
        return host;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with CustomHeaderAuthentication.
     * @return customHeaderAuthenticationCredentials
     */
    public CustomHeaderAuthenticationCredentials getCustomHeaderAuthenticationCredentials() {
        return customHeaderAuthenticationManager;
    }

    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        parameters.put("host",
                new SimpleEntry<Object, Boolean>(this.host, false));
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }

    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "{host}";
            }
        }
        if (environment.equals(Environment.ENVIRONMENT2)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "http://localhost:3000/colending";
            }
        }
        if (environment.equals(Environment.ENVIRONMENT3)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://colend-api.credavenue.com/colending";
            }
        }
        return "{host}";
    }

    /**
     * Converts this KrazybeeClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "KrazybeeClient [" + "environment=" + environment + ", host=" + host
                + ", httpClientConfig=" + httpClientConfig + ", authManagers=" + authManagers + "]";
    }

    /**
     * Builds a new {@link KrazybeeClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link KrazybeeClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.host = getHost();
        builder.httpClient = getHttpClient();
        builder.apiKey = getCustomHeaderAuthenticationCredentials().getApiKey();
        builder.authManagers = authManagers;
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(configBldr -> configBldr =
                ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link KrazybeeClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private String host = "https://colend-uat-01-api.credavenue.in/colending";
        private HttpClient httpClient;
        private String apiKey = "";
        private Map<String, AuthManager> authManagers = null;
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for CustomHeaderAuthentication.
         * @param apiKey String value for apiKey.
         * @return Builder
         */
        public Builder customHeaderAuthenticationCredentials(String apiKey) {
            if (apiKey == null) {
                throw new NullPointerException("ApiKey cannot be null.");
            }
            this.apiKey = apiKey;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * For UAT environment
         * @param host The host for client.
         * @return Builder
         */
        public Builder host(String host) {
            this.host = host;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Builds a new KrazybeeClient object using the set fields.
         * @return KrazybeeClient
         */
        public KrazybeeClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig);

            return new KrazybeeClient(environment, host, httpClient, httpClientConfig, apiKey,
                    authManagers, httpCallback);
        }
    }
}